// Payroll Related Data Constructors Index
// Centralized exports for all payroll related data constructor functions

export {
  PayrollRelatedDataConstructor,
  payrollRelatedDataConstructor
} from './data_constructors/payrollRelatedDataConstructor.js';

// Export calculation functions
export {
  calculatePayrollTaxes,
  calculateSupplementaryPay,
  calculateEmployeeBenefits,
  calculateTotalPayrollRelated,
  calculateManagementSubtotals,
  calculateNonManagementSubtotals,
  calculateLocationTotals,
  calculateHotelTotals,
  calculateEmployeeRoomRatio
} from './related_calculations.js';

// Export utility functions
export {
  transformRelatedApiToFrontend,
  transformRelatedFrontendToApi,
  validateRelatedData,
  getRelatedFieldValue,
  setRelatedFieldValue,
  createDefaultRelatedRow,
  getRequiredFieldsForPageType,
  calculateRelatedTotals,
  formatCurrency,
  formatPercentage,
  allowOnlyNumbers,
  findMatchingPayrollRow,
  generateRelatedRowId,
  hasRelatedDataChanges,
  getRelatedDataSummary
} from './related_utils.js';

// Export input handlers
export {
  formatMoney,
  getTaxPercentage,
  getTaxTotal,
  handleTaxPercentageInput,
  handleTaxPercentageFocus,
  handleTaxPercentageBlur,
  handleTaxTotalInput,
  handleTaxTotalFocus,
  handleTaxTotalBlur,
  getVacation,
  getRelocation,
  getSeverenceIndemnity,
  getOther,
  handleVacationInput,
  handleVacationFocus,
  handleVacationBlur,
  handleRelocationInput,
  handleRelocationFocus,
  handleRelocationBlur,
  handleSeverenceIndemnityInput,
  handleSeverenceIndemnityFocus,
  handleSeverenceIndemnityBlur,
  handleOtherInput,
  handleOtherFocus,
  handleOtherBlur,
  getMedical,
  getUniforms,
  getEmployeeMeal,
  getTransport,
  getTelephone,
  getAirTicket,
  getBenefitsOther,
  handleMedicalInput,
  handleMedicalFocus,
  handleMedicalBlur,
  handleUniformsInput,
  handleUniformsFocus,
  handleUniformsBlur,
  handleEmployeeMealInput,
  handleEmployeeMealFocus,
  handleEmployeeMealBlur,
  handleTransportInput,
  handleTransportFocus,
  handleTransportBlur,
  handleTelephoneInput,
  handleTelephoneFocus,
  handleTelephoneBlur,
  handleAirTicketInput,
  handleAirTicketFocus,
  handleAirTicketBlur,
  handleBenefitsOtherInput,
  handleBenefitsOtherFocus,
  handleBenefitsOtherBlur
} from './input_handlers.js';

// Export calculation handlers
export {
  calculateSubTotalManagementTaxPercentageLocal,
  calculateSubTotalManagementTaxTotalLocal,
  calculateSubTotalNonManagementTaxPercentageLocal,
  calculateSubTotalNonManagementTaxTotalLocal,
  calculateLocationTotalTaxPercentageLocal,
  calculateLocationTotalTaxTotalLocal,
  calculateHotelTotalTaxPercentageLocal,
  calculateHotelTotalTaxTotalLocal,
  calculateEmployeeRoomRatioTaxPercentageLocal,
  calculateEmployeeRoomRatioTaxTotalLocal,
  calculateSubTotalManagementVacationLocal,
  calculateSubTotalManagementRelocationLocal,
  calculateSubTotalManagementSeverenceIndemnityLocal,
  calculateSubTotalManagementOtherLocal,
  calculateSubTotalNonManagementVacationLocal,
  calculateSubTotalNonManagementRelocationLocal,
  calculateSubTotalNonManagementSeverenceIndemnityLocal,
  calculateSubTotalNonManagementOtherLocal,
  calculateLocationTotalVacationLocal,
  calculateLocationTotalRelocationLocal,
  calculateLocationTotalSeverenceIndemnityLocal,
  calculateLocationTotalOtherLocal,
  calculateHotelTotalVacationLocal,
  calculateHotelTotalRelocationLocal,
  calculateHotelTotalSeverenceIndemnityLocal,
  calculateHotelTotalOtherLocal,
  calculateEmployeeRoomRatioVacationLocal,
  calculateEmployeeRoomRatioRelocationLocal,
  calculateEmployeeRoomRatioSeverenceIndemnityLocal,
  calculateEmployeeRoomRatioOtherLocal,
  calculateSubTotalManagementMedicalLocal,
  calculateSubTotalManagementUniformsLocal,
  calculateSubTotalManagementEmployeeMealLocal,
  calculateSubTotalManagementTransportLocal,
  calculateSubTotalManagementTelephoneLocal,
  calculateSubTotalManagementAirTicketLocal,
  calculateSubTotalManagementBenefitsOtherLocal,
  calculateSubTotalNonManagementMedicalLocal,
  calculateSubTotalNonManagementUniformsLocal,
  calculateSubTotalNonManagementEmployeeMealLocal,
  calculateSubTotalNonManagementTransportLocal,
  calculateSubTotalNonManagementTelephoneLocal,
  calculateSubTotalNonManagementAirTicketLocal,
  calculateSubTotalNonManagementBenefitsOtherLocal,
  calculateLocationTotalMedicalLocal,
  calculateLocationTotalUniformsLocal,
  calculateLocationTotalEmployeeMealLocal,
  calculateLocationTotalTransportLocal,
  calculateLocationTotalTelephoneLocal,
  calculateLocationTotalAirTicketLocal,
  calculateLocationTotalBenefitsOtherLocal,
  calculateHotelTotalMedicalLocal,
  calculateHotelTotalUniformsLocal,
  calculateHotelTotalEmployeeMealLocal,
  calculateHotelTotalTransportLocal,
  calculateHotelTotalTelephoneLocal,
  calculateHotelTotalAirTicketLocal,
  calculateHotelTotalBenefitsOtherLocal,
  calculateEmployeeRoomRatioMedicalLocal,
  calculateEmployeeRoomRatioUniformsLocal,
  calculateEmployeeRoomRatioEmployeeMealLocal,
  calculateEmployeeRoomRatioTransportLocal,
  calculateEmployeeRoomRatioTelephoneLocal,
  calculateEmployeeRoomRatioAirTicketLocal,
  calculateEmployeeRoomRatioBenefitsOtherLocal
} from './calculation_handlers.js';

// Export utility handlers
export {
  allowOnlyNumbersAndDecimal,
  isSyncedWithRoomRevenue,
  handleTotalRoomsChange,
  handleTotalRoomsBlur,
  syncWithRoomRevenue,
  refreshTable,
  handleBeforeUnload,
  applyAdvancedSettings,
  cancelAdvancedSettings,
  clearYearSelection,
  ensureCountDataStructure,
  ensureSalaryDataStructure,
  getMonthlyCountValue,
  setMonthlyCountValue,
  handlePayrollCellEditLocal,
  handlePayrollCellInput,
  handlePayrollCellFocus,
  handleModalSalaryInput,
  handleModalSalaryFocus,
  handleModalSalaryBlur,
  handleTableSalaryInput,
  handleTableSalaryFocus,
  handleTableSalaryBlur,
  handleTableCountInput,
  handleTableCountFocus,
  handleTableCountBlur
} from './utility_handlers.js';
