/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCategoryModal: typeof import('./src/components/ui/contractor_estimator/AddCategoryModal.vue')['default']
    Alert: typeof import('./src/components/ui/Alert.vue')['default']
    DataRecoveryModal: typeof import('./src/components/ui/DataRecoveryModal.vue')['default']
    EmployeeBenefitsTable: typeof import('./src/components/ui/payroll/EmployeeBenefitsTable.vue')['default']
    ExpenseErrorState: typeof import('./src/components/ui/expense/ExpenseErrorState.vue')['default']
    ExpenseNoProjectSelectedState: typeof import('./src/components/ui/expense/ExpenseNoProjectSelectedState.vue')['default']
    ExpenseNoYearsSelectedState: typeof import('./src/components/ui/expense/ExpenseNoYearsSelectedState.vue')['default']
    FnbNoDataState: typeof import('./src/components/ui/fnb/FnbNoDataState.vue')['default']
    FnbNoProjectSelectedState: typeof import('./src/components/ui/fnb/FnbNoProjectSelectedState.vue')['default']
    FnbNoYearsSelectedState: typeof import('./src/components/ui/fnb/FnbNoYearsSelectedState.vue')['default']
    FoodBeverageProfitLoss: typeof import('./src/components/ui/reports/FoodBeverageProfitLoss.vue')['default']
    LoadingState: typeof import('./src/components/ui/payroll/LoadingState.vue')['default']
    MarketSegmentationTables: typeof import('./src/components/ui/MarketSegmentationTables.vue')['default']
    NewProjectModal: typeof import('./src/components/ui/project_budget/NewProjectModal.vue')['default']
    NoCategoriesModal: typeof import('./src/components/ui/contractor_estimator/NoCategoriesModal.vue')['default']
    NoDataState: typeof import('./src/components/ui/expense/NoDataState.vue')['default']
    NoPayrollDataState: typeof import('./src/components/ui/payroll/NoPayrollDataState.vue')['default']
    NoProjectSelectedState: typeof import('./src/components/ui/banquet/NoProjectSelectedState.vue')['default']
    NoYearsSelectedState: typeof import('./src/components/ui/banquet/NoYearsSelectedState.vue')['default']
    OodNoProjectSelectedState: typeof import('./src/components/ui/ood/OodNoProjectSelectedState.vue')['default']
    OodNoYearsSelectedState: typeof import('./src/components/ui/ood/OodNoYearsSelectedState.vue')['default']
    PayrollNoProjectSelectedState: typeof import('./src/components/ui/payroll/PayrollNoProjectSelectedState.vue')['default']
    PayrollNoYearsSelectedState: typeof import('./src/components/ui/payroll/PayrollNoYearsSelectedState.vue')['default']
    PayrollRelatedTabs: typeof import('./src/components/ui/payroll/PayrollRelatedTabs.vue')['default']
    PayrollSkeleton: typeof import('./src/components/ui/skeleton/PayrollSkeleton.vue')['default']
    PayrollTaxesTable: typeof import('./src/components/ui/payroll/PayrollTaxesTable.vue')['default']
    ProjectSelector: typeof import('./src/components/ui/ProjectSelector.vue')['default']
    ReceiptsNoYearsSelectedState: typeof import('./src/components/ui/receipts/ReceiptsNoYearsSelectedState.vue')['default']
    ReportControls: typeof import('./src/components/ui/reports/ReportControls.vue')['default']
    ReportPageLayout: typeof import('./src/components/layouts/ReportPageLayout.vue')['default']
    ReportSectionNoData: typeof import('./src/components/ui/reports/ReportSectionNoData.vue')['default']
    ReportSectionNoDataRow: typeof import('./src/components/ui/reports/ReportSectionNoDataRow.vue')['default']
    ReportSelector: typeof import('./src/components/ui/reports/ReportSelector.vue')['default']
    ReportsNoDataState: typeof import('./src/components/ui/reports/ReportsNoDataState.vue')['default']
    ReportsNoProjectSelectedState: typeof import('./src/components/ui/reports/ReportsNoProjectSelectedState.vue')['default']
    ReportsNoYearsSelectedState: typeof import('./src/components/ui/reports/ReportsNoYearsSelectedState.vue')['default']
    RoomErrorState: typeof import('./src/components/ui/room/RoomErrorState.vue')['default']
    RoomNoProjectSelectedState: typeof import('./src/components/ui/room/RoomNoProjectSelectedState.vue')['default']
    RoomNoYearsSelectedState: typeof import('./src/components/ui/room/RoomNoYearsSelectedState.vue')['default']
    RoomProfitLoss: typeof import('./src/components/ui/reports/RoomProfitLoss.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectProjectModal: typeof import('./src/components/ui/contractor_estimator/SelectProjectModal.vue')['default']
    SettingsModal: typeof import('./src/components/ui/SettingsModal.vue')['default']
    Sidebar: typeof import('./src/components/ui/Sidebar.vue')['default']
    SupplementaryPayTable: typeof import('./src/components/ui/payroll/SupplementaryPayTable.vue')['default']
    TotalTable: typeof import('./src/components/ui/payroll/TotalTable.vue')['default']
  }
}
