/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCategoryModal: typeof import('./src/components/ui/contractor_estimator/AddCategoryModal.vue')['default']
    Alert: typeof import('./src/components/ui/Alert.vue')['default']
    DataRecoveryModal: typeof import('./src/components/ui/DataRecoveryModal.vue')['default']
    EmployeeBenefitsTable: typeof import('./src/components/ui/payroll/EmployeeBenefitsTable.vue')['default']
    ErrorState: typeof import('./src/components/ui/expense/ErrorState.vue')['default']
    FoodBeverageProfitLoss: typeof import('./src/components/ui/reports/FoodBeverageProfitLoss.vue')['default']
    LoadingState: typeof import('./src/components/ui/payroll/LoadingState.vue')['default']
    MarketSegmentationTables: typeof import('./src/components/ui/MarketSegmentationTables.vue')['default']
    NewProjectModal: typeof import('./src/components/ui/project_budget/NewProjectModal.vue')['default']
    NoDataState: typeof import('./src/components/ui/expense/NoDataState.vue')['default']
    NoPayrollDataState: typeof import('./src/components/ui/payroll/NoPayrollDataState.vue')['default']
    NoProjectSelectedState: typeof import('./src/components/ui/banquet/NoProjectSelectedState.vue')['default']
    NoYearsSelectedState: typeof import('./src/components/ui/banquet/NoYearsSelectedState.vue')['default']
    PayrollRelatedTabs: typeof import('./src/components/ui/payroll/PayrollRelatedTabs.vue')['default']
    PayrollTaxesTable: typeof import('./src/components/ui/payroll/PayrollTaxesTable.vue')['default']
    ProjectSelector: typeof import('./src/components/ui/ProjectSelector.vue')['default']
    ReportSelector: typeof import('./src/components/ui/reports/ReportSelector.vue')['default']
    RoomProfitLoss: typeof import('./src/components/ui/reports/RoomProfitLoss.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/ui/SettingsModal.vue')['default']
    Sidebar: typeof import('./src/components/ui/Sidebar.vue')['default']
    SupplementaryPayTable: typeof import('./src/components/ui/payroll/SupplementaryPayTable.vue')['default']
    TotalTable: typeof import('./src/components/ui/payroll/TotalTable.vue')['default']
  }
}
